### ISSUE TITLE
Yet another broken model for glTF serializer fixing

### ISSUE THREAD

**Issue by JulianGro** [overte-org/overte#546]
Roughly how it is supposed to look:
![Bildschirmfoto vom 2023-08-04 11-43-11](https://github.com/overte-org/overte/assets/11144627/fc875fe1-a00f-458b-8ba5-b4a66a0391d0)

How it looks in Overte 2023.07.1-rc3:
![overte-snap-by-JulianGro-on-2023-08-04_11-39-52](https://github.com/overte-org/overte/assets/11144627/13d2a81e-9374-4f5c-8590-ac9912f4e930)

https://data.moto9000.moe/zen_Overte_1.glb
"Interdimensional zen gallery space" (https://skfb.ly/o6BI8) by Foodbird is licensed under Creative Commons Attribution (http://creativecommons.org/licenses/by/4.0/).

**Comment by SilverfishVR** [comment]
Uh, I know this one.
If you have a model with with a skinned mesh (with armature) in combination with one or more other objects that does not have an armature, parts of those objects seems to be missing (or in a Weird position/size).
here is the island with no armature (don't mind the beached fish 🐟): 
http://silverfish-freestuff.s3.amazonaws.com/TestStuff/GLTF_armature_import/island_no%20armature.glb

Some simpler examples:
Broken: http://silverfish-freestuff.s3.amazonaws.com/TestStuff/GLTF_armature_import/2_objects_1_armature.glb
Good: http://silverfish-freestuff.s3.amazonaws.com/TestStuff/GLTF_armature_import/2_objects_2_armatures.glb

![Screenshot 2023-08-09 212013](https://github.com/overte-org/overte/assets/53531160/f23f19fb-374e-4230-9d4c-3587e305329e)
And their corresponding blend files:
http://silverfish-freestuff.s3.amazonaws.com/TestStuff/GLTF_armature_import/GLTF-Armature_2_objects_1_armatures.blend
http://silverfish-freestuff.s3.amazonaws.com/TestStuff/GLTF_armature_import/GLTF-Armature_2_objects_2_armatures.blend

indecently, some combinations af armatures and objects are also good examples of models that crash interface, but actually also sometimes break the Blender exporter, I will make a separate issue if I figure out some nice reproduceable examples

**Comment by HifiExperiments** [comment]
maybe fixed by cgltf?

**Comment by JulianGro** [comment]
The model now has the right orientation in 9bbd04c928c67cd6055395c7ed94fff3d0526d37, but is still broken.
![overte-snap-by--on-2024-03-03_16-26-11](https://github.com/overte-org/overte/assets/11144627/381b7d55-8c98-4869-9813-02b3f85c85e7)
